### PR TITLE
Fixing delete payload... causes 500 when empty

### PR DESCRIPTION
**Pull request by claygorman**
I made a change in the code that fixes an error I was having for deleting a deployment specifically.

### CODE REVIEW

**Comment by claygorman** [comment]
@maclof let me know if you have any questions or concerns. Would love to see this merged! Thanks

**Comment by maclof** [comment]
Hey @claygorman 

Which version of the Kubernetes server are you using this with that's causing the issue?

I'm fine with the change, just not experienced this myself.

**Comment by claygorman** [comment]
@maclof not a problem at all. We are running version server version 1.6.1.

It was definitely a weird issue I did not expect.

**Comment by claygorman** [comment]
Thank you @maclof for merging! I really appreciate your time. To take advantage of this merge from packagist i have `"maclof/kubernetes-client": "^0.2.0",` would this still work? 

If I recall packagist needs updating manually.

**Comment by maclof** [comment]
@claygorman the latest version is 0.2.1 so you would just need to composer update

**Pull request merged**
