### PR TITLE
Return API response instead of 'true'

### PR DESCRIPTION
**Pull request by mwadon**

### CODE REVIEW

**Comment by maclof** [comment]
Can you provide examples of API responses from both calls?

**Comment by mwadon** [comment]
@maclof Yes, sure:
https://docs.openshift.com/container-platform/3.6/rest_api/kubernetes_v1.html#create-a-pod
https://docs.openshift.com/container-platform/3.6/rest_api/kubernetes_v1.html#replace-the-specified-pod

**Comment by maclof** [comment]
Can you do the same for the delete/deleteByName methods? Should return a status response:
https://docs.openshift.com/container-platform/3.6/rest_api/kubernetes_v1.html#v1-status

**Comment by mwadon** [comment]
@maclof fixed

**Comment by maclof** [comment]
@mwadon perfect, thank you!

**Pull request merged**
