### PR TITLE
Add JSONPath support to retrieve model data

### PR DESCRIPTION
**Pull request by fernandocarletti**

### CODE REVIEW

**Comment by maclof** [comment]
This is sweet, thank you.

Travis builds seem to be failing with an issue with the mockery dependency

**Comment by fernandocarletti** [comment]
Oh, true. PHP 5.6 is reaching its end of life in December, should we push for at least PHP 7.0+? I can do the upgrade in the PR #42.

**Comment by fernandocarletti** [comment]
Actually, 7.1+, since 7.0 is also reaching its EOL: https://upgradeyourphp.com/

**Comment by fernandocarletti** [comment]
Btw, Merge the #42 first, please. This PR was branched from that one.

**Pull request merged**
