### PR TITLE
Fix return annotion for exec

### PR DESCRIPTION
**Pull request by danijelk**
Response can be an array depending on what 'std*' input you give it, this fixes phpstan.

### CODE REVIEW

**Comment by michaelbutler** [comment]
Pull in the latest `master` updates if you want to fix the build error.

Speaking of this change, it does make sense as `sendRequest` could return a `string` and not an `array`; however from what I understand that should only occur when an error occurs -- the k8s API should always return a valid JSON unless it could not be reached (e.g. proxy server is down). In my personal opinion we should get to the point where `sendRequest` either returns an array OR throws an exception, instead of trying to support it returning string. Unless I'm missing some other use case.

**Comment by maclof** [comment]
@michaelbutler if I recall correctly, sendRequest returns a mixed response, not necessarily an array or string
There is a watch method that uses a streamed response for example: https://github.com/maclof/kubernetes-client/blob/e5a21c4cc6536d930f8f7fda028262a23963282f/src/Repositories/Repository.php#L338

**Comment by michaelbutler** [comment]
Oh, thanks I see that now. 

```php
			if (!empty($options['stream'])) {
				return $response;
			}
```

so regarding this PR, the typehint on `exec` could just also be `mixed` due to the possibility of multiple things.

**Comment by danijelk** [comment]
updated to mixed as per conversation.

**Comment by maclof** [comment]
Thanks! :)

**Pull request merged**
